### PR TITLE
Remove item from map after some time

### PR DESCRIPTION
**Pull request by aosyatnik**
After 60 seconds item is removed from the map.

### CODE REVIEW

**Review by matigramirez — COMMENTED** [review]
The 20 seconds item ownership works perfect. I think the total time of the item is not working as intended because I checked twice and the item stayed on the ground for 80 seconds, maybe the ownership time is getting added to the total time?

**Comment by aosyatnik** [comment]
@matigramirez yes, you are right. The timer to remove the item starts right after the owner changed to null. So it's 60 (wait for remove) + 20 (wait for the owner). Do you think, that both timers should start at the same time?

**Comment by matigramirez** [comment]
@aosyatnik 80 seconds felt like too long for me as total time but it's up to you, just wanted to point it out in case it wasn't intentional

**Comment by aosyatnik** [comment]
@matigramirez , fixed timers.

**Review by matigramirez — APPROVED** [review]
Cool, 60 seconds in total feels better in game

**Pull request merged**
